name: Handle Release

#on:
#  push:
#    tags:
#      - "v*.*.*"
on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}
    name: "Create release-artifacts"

    env:
      artifact_name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Copy files
        shell: bash
        run: |
          mv dist ${{ env.artifact_name }}

      #- name: Create archive (Unix)
      #  shell: bash
      #  run: |
      #    zip -r ${{ env.artifact_name }}.zip ${{ env.artifact_name }}
      - uses: vimtor/action-zip@v1.2
        with:
          files: ${{ env.artifact_name }}/
          dest: ${{ env.artifact_name }}.zip

      # Needs "Read and write permission" under "Workflow permissions" on https://github.com/chrismile/naga_cross/settings/actions.
      - name: Create release
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.artifact_name }}.zip
